### ISSUE TITLE
Autofocus camera

### ISSUE THREAD

**Issue by tejasmr** [tejas1904/OurVision#10]
Related to autofocus camera

- [x] Figure out how to control the camera
- [x] Figure out UVC controls in linux
- [x] Write a sample program to prove the working of the Autofocus camera using OpenCV

Useful links:
Official Website: https://www.arducam.com/product/arducam-ov5648-auto-focus-usb-camera-ub0238-6/
ArduCam UVC Guide: https://www.arducam.com/docs/uvc-camera-module/use-arducam-uvc-cameras-on-linux/uvc-cameras-on-linux-command-line/
OpenCV Video API: https://docs.opencv.org/master/d4/d15/group__videoio__flags__base.html#gaeb8dd9c89c10a5c63c139bf7c4f5704d

**Comment by tejasmr** [comment]
Added official website link

**Comment by TheNova22** [comment]
- Instead of libcamera used for the capturing images, I found it effective to use _fswebcam_ as it works with Arducam
- Hence for the cmd mentioned in button_handler.py, we can use the following command: 
`cmd = "fswebcam -d /dev/video0 -r 2500x2500 -v -S 10 --set brightness=100% --no-banner " + INPUT_IMAGE_PATH`
- I have set the resolution as 2500x2500, but it then autosizes to 2592x1944 as it is one of the set resolutions in it

**Comment by TheNova22** [comment]
To install fswebcam, the command will be
`sudo apt-get install fswebcam`
